"""initial schema: users timesheets approval_records holidays

Revision ID: 4e4d259e39e2
Revises:
Create Date: 2026-06-10 02:44:48.907519

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4e4d259e39e2"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "holidays",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("holidays", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_holidays_date"), ["date"], unique=True)
        batch_op.create_index(batch_op.f("ix_holidays_id"), ["id"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("supervisor_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["supervisor_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_users_employee_id"), ["employee_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_users_id"), ["id"], unique=False)

    op.create_table(
        "timesheets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("hours", sa.Float(), nullable=False),
        sa.Column("project_tag", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("tags", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("timesheets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_timesheets_date"), ["date"], unique=False)
        batch_op.create_index(batch_op.f("ix_timesheets_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_timesheets_project_tag"), ["project_tag"], unique=False)

    op.create_table(
        "approval_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timesheet_id", sa.Integer(), nullable=False),
        sa.Column("approver_id", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["approver_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["timesheet_id"],
            ["timesheets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("approval_records", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_approval_records_id"), ["id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("approval_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_approval_records_id"))

    op.drop_table("approval_records")
    with op.batch_alter_table("timesheets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_timesheets_project_tag"))
        batch_op.drop_index(batch_op.f("ix_timesheets_id"))
        batch_op.drop_index(batch_op.f("ix_timesheets_date"))

    op.drop_table("timesheets")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_id"))
        batch_op.drop_index(batch_op.f("ix_users_employee_id"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("holidays", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_holidays_id"))
        batch_op.drop_index(batch_op.f("ix_holidays_date"))

    op.drop_table("holidays")
    # ### end Alembic commands ###
